### ISSUE TITLE
Provide a better formatted plugin description and plugin name

### ISSUE THREAD

**Issue by markiewb** [Chris2011/NbQuickSearchExtender#1]
![2016-01-25_20h43_15](https://cloud.githubusercontent.com/assets/1857095/12562211/51c4c46c-c3a4-11e5-9d87-9b7807fa79cc.png)

**Comment by Chris2011** [comment]
The plugin description I agree, it was copied from the readme.md file so it is markdown, unfortunately NB and the plugin page can't handle this... Will update it soon.

The name is a private convention from me to Put a Nb infront of my plugin, where it makes sense. If you have a better name, let me knows it.

Thx.

**Comment by markiewb** [comment]
Use simple HTML instead! Github also supports rendering that within a README.MD. This way it can also be copied easily to the plugin center as a description. This is my workflow.

For example: https://raw.githubusercontent.com/markiewb/nb-codeoutline/master/README.md

The name topic: Ah, OK. I thought it was an artefact of a non-configured name. Then keep it as it is! CU

**Comment by Chris2011** [comment]
Done in 1.2.1
